name: webshop-dev

services:
  app:
    build: ./app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=webshop
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    build: 
      context: .
      dockerfile: db/Dockerfile.dev
    environment:
      POSTGRES_DB: webshop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data:
